image: python:3.12-slim

stages:
  - audit

rocketchat_audit:
  stage: audit

  script:
    - python3 --version
    - python3 rocketchat_audit.py

  artifacts:
    when: always
    paths:
      - rocketchat_users.csv
    expire_in: 30 days